### ISSUE TITLE
Overwrite data with same dataset names

### ISSUE THREAD

**Issue by MikeDuf** [Silly-V/Adobe-Illustrator#18]
Hi,
I'd like to know if this is an option and how to do it.
I have a lot of data sometimes numbers are the same and its hard for me to find every numbers that repeat.

Thanks!

**Comment by Silly-V** [comment]
In your text-processing program such as Excel, can you find any macros or add-ons which remove duplicates?
I suppose sometime I can make this a checkbox-feature in the VI settings. This, and custom-start increments as well as zero-padding rules.

**Comment by Silly-V** [comment]
Since the VariableImporter is more concerned with data-import rather than data manipulation (except for maybe the transpose button), at this time I suggest using the capabilities of the spreadsheet processing softwares to remove duplicates during the step when data is created. Or sanitized. Please see this link for the Excel solution: https://www.howtogeek.com/198052/how-to-remove-duplicate-rows-in-excel/
