### ISSUE TITLE
Auto Binding not working, after Image File not found

### ISSUE THREAD

**Issue by hermify** [Silly-V/Adobe-Illustrator#25]
Hi there,
im using the Illustrator Importscript and added Image-Variables.
I noticed that if an Image-File is not found, because of missing file,
the script is aborting, right after the success-Message. 

(Right after I get a message, that 
"Variable Data Imported",
Your variable data has been imported. It contains....".)

But after clicking on "OK"-Button, there is no Auto-Binding of the other Variables.

Is this a Bug? Normaly it should Bind the imported Variables. 
Other Variables are imported within this missing image file, but not binded.

**Comment by Silly-V** [comment]
This is our actual default behavior - as when an image is not found it will cause alert boxes to appear and prompt the user to re-link the image manually or ignore the broken link. This will happen each time the dataset is changed, so this is a non-desired workflow. Furthermore, even if 90/100 files are found - this will cause an effect of having the possible perception that all files were located - so after a time-intensive batch-process the actions will stall out with a broken-link box on the 90th item , potentially upsetting the flow of a batch process task.
For the above reasons, the choice is to allow import of non-found data but only enable auto binding of found existing data due to how images are handled.
In order to get the best result, please try to use a blank 'placeholder' image to fill your missing files or cells which are intended to be blank. This way the variables could be automatically bound and Illustrator can keep its satisfaction with found image files.

**Comment by hermify** [comment]
Hi there,
thanks for detailed answer. 

My problem is, that if only one image file is not found correctly, 
i would like to enable auto binding for the found existing data. But i think, we'll use image fallbacks and i'll check with a script, if files exists, before i run the importer-script.

**Comment by Silly-V** [comment]
It's a good opportunity here to highlight the differences in variable data handling between Illustrator and InDesign, as ID's behavior is not to throw up obtrusive alert dialogs but rather it treats missing images as non-filled frames of sorts (comparatively speaking).  So whereas conditional text-wrap around an image item is a whole mission in Illustrator, it's just the default behavior in InDesign. <-- this is talking about having a circle image inside a paragraph and wanting text to wrap around the image, except in some cases the image is not in the data. In this case with Illustrator one would have to also use a visibility variable - most likely.
