### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by interludic** [Silly-V/Adobe-Illustrator#34]
Although none missing in the 'test'
it seems to find only 7/24 images, however they are there. Some of which have already been referenced previously.

**Comment by interludic** [comment]
VariableImporter.jsx

**Comment by Silly-V** [comment]
Do you have any screenshots of this issue?

**Comment by Huaba93** [comment]
I had this issue too but it was my fault. There were typos in some filenames. If this error occurs, nothing works anymore. So maybe it could be implemented a little bit more fail safe.

**Comment by Silly-V** [comment]
The test logs which say there's only x of y images is the fail-safe: if your images are missing then you know about it. It will still import the data but it won't auto-bind the variables because a missing image would trigger Illustrator image alerts and the users would have a potential to think their import was OK as they may forget about seeing extra script warnings. However, if they want to import it regardless I could perhaps add a Yes/No dialog to say "Not all images were located. Do you want to use auto-binding?".

**Comment by Huaba93** [comment]
Now that I know how it works, it is good for me as it is.
