### ISSUE TITLE
Missing functionality compared to the legacy version

### ISSUE THREAD

**Issue by iconickgr** [Silly-V/Adobe-Illustrator#35]
Just wanted to ask, if there's a way to add back the option of "variable name "in the data set name assignment. It was a really useful feature in the legacy version and it seems to be missing in the most recent one.

**Comment by Silly-V** [comment]
It's there, but unfortunately in your case you may have to go to your Windows resolution settings and set it to 100%, then look at the dropdown inside the drodown fields in the dataset naming dialog. When the UI scaling is at default 100%, the truncated dropdown items are visible, so you should see the variable's names listed in there now.

**Comment by iconickgr** [comment]
Thanks for your reply!
Indeed it was the text scaling in Windows display settings (mine was set at 125% instead of the default 100%).
And thanks for this script, you've saved a lot of time for a lot of people :)

**Comment by Silly-V** [comment]
If you rarely have to change the dataset names, you can change your resolution scaling settings back each time. Otherwise if you are technically-inclined you could try to edit the JSON document inside the Documents/Adobe Scripts/VariableImporter folder that gets created and is used by the script to store settings.
