### ISSUE TITLE
Notes for images are reset after import

### ISSUE THREAD

**Issue by Huaba93** [Silly-V/Adobe-Illustrator#43]
Hi. For the auto binding we use the note field. After an import the note gets cleared for referenced images. Text fields survive. This is quite annoying, because I have to set everything again with every test. 
Am I doing something wrong, is it a mistake or is there no other way?

**Comment by Silly-V** [comment]
Yes, this is an obscure yet known issue: when you put notes on a placed file and replace its variable image path, the notes disappear even with no script. So it will happen regardless. However, we can work around it by taking your placed file and ensuring it is wrapped inside of a group. Then you place all your necessary notes on the group and not the placed file. Now, when you change the dataset, your placed file won't have any notes, but you can still select it via notes in actions because you can target its parent group.
