### ISSUE TITLE
Problem when there is a dot in the dataset name

### ISSUE THREAD

**Issue by anoth12** [Silly-V/Adobe-Illustrator#45]
the dataset that I set is
0922.9123.0001
0922.9123.0002
0922.9123.0003

when export to PNG file name is incomplete, becomes
0922.9123.0001.png
0922.png
0922.png

at the time, finally only 2 were png files namely
0922.9123.0001.png
0922.png

this happens because there is the same file name.

how to solve the problem of naming this dataset so that it is automatically replaced, for example point (.) to underscore (_)?

**Comment by Silly-V** [comment]
This looks like a native Illustrator internal issue, I suggest inputting data using underscores first, then using the Bridge Batch Rename tool to edit the file names to place the dots back in. Or you can do your entire export twice since the names are properly set if the badly-named file already exists. This 2nd option is not ideal by any means, but it's good to know this behavior.
To officially and formally address this bug, please enter a request at Illustrator's user-voice website: https://illustrator.uservoice.com/
