### ISSUE TITLE
Variable Importer v8.1.1 visibility import does not process last record

### ISSUE THREAD

**Issue by u2junk** [Silly-V/Adobe-Illustrator#5]
I want to start off saying, I absolutely love your script. You have made Adobe Illustrator's Variables function a usable feature. I just discovered your script a few weeks ago, by watching a tutorial video on YouTube. 

So If I am doing something wrong, please say so.

The issue that I am having, only exists when I import variables for "#visibility" of objects. The script works perfectly in every way, except for capture of the last Record/Data Set. This does not seem to matter how many "#visibility" Records/Data Sets are being imported. The variables for that set and all sets are imported, only the last Record/Data Set does not get captured. I can fix this pretty easily, being as the variables were already imported I can set up the visibility of the objects and just click capture Data Set and rename it accordingly. However, I would absolutely love it if you can fix this bit of automation for me. 

I am using the "#visibility" functions with a Unicode.txt file created from Excel 2010. The "Use Headers" and "Transpose Data" check boxes are checked. The character I am using for the visibility switches is "x". All other script presets are kept at default.

I have not had any problems with the import of text into text objects. That portion of the script seems to work perfectly for all Records/Data Sets. This even works with Unicode text, thank you for that by the way. The only problems that I have with the "@image" seems to be due with files named with Unicode characters, and that seems to be an Adobe problem, not a problem with your script, from what I can tell. I have not yet had the opportunity to test out the charts and graphs.

The version of Adobe Illustrator that I am using is Adobe Illustrator CC 2015.3.1 v20.1.0 (64-bit) This is the newest version of Illustrator CC to my knowledge. I have tried your script on older builds of Ai CC 2015 with the same result.

Thank you again, for this script!

**Comment by Silly-V** [comment]
Thank you for trying out the importer and using it in your workflow!
Indeed, the behavior you observe does exist and you're not doing anything wrong. However, this behavior is a result of a set of intersecting circumstances and can be fixed easily. The reason this occurs in your case is because there is a situation where the first row of the CSV is not populated with characters all the way to the end of its cells. Since you are using the handy capabilities of the visibility variable, you're electing to keep some blank information on the end of the row, which has results in the default csv read-in behavior of _truncating the data based on the first row_.
**To easily fix the issue, make sure that the top-most row of your data has a 'false' in the last cell of that first variable.**
Now, when you do Transpose in your import dialog, the last record will come through!
Let me know if this suggestion brings you back to satisfactory?

**Comment by u2junk** [comment]
Thank you very much, for your detailed answer. That did fix the problem for me. I'm very grateful for your time. Your script is the only thing that I have found, that makes Ai's variables usable.

I nearly switched to Corel Draw for the majority of my variable data workflow.

I'm curious, would you be willing to add a data import wizard that is similar to Corel Draw? The wizard enables import from several file types to include Excel.xlsx. It then shows the data fields from the file being imported and allows you to select which objects on the artboard they match up with.

I certainly understand that this isn't a simple fix, and would require compensation.

**Comment by Silly-V** [comment]
Hey, I'm going to go ahead and close this issue - let us continue this discussion via email: please write to vasily.hall@gmail.com
